export const ACTION_TYPES = {
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  CHANGE_INCREASE_QUANTITY: "CHANGE_INCREASE_QUANTITY",
  CHANGE_DECREASE_QUANTITY: "CHANGE_DECREASE_QUANTITY",
};
